### PR TITLE
[WIP-ish] Automation, updates

### PR DESCRIPTION
**Pull request by notjosh**
Whew, this repo seemed a bit unloved so I jumped in. Waiting for the next `SFBAudioEngine-dependencies.tar.bz2` seems unlikely, so let's make it so everyone can do it.

Note: I've really only catered directly for my use case (OS X, not iOS). There's also some leftover targets in the `.xcodeproj`s and inconsistency with build settings. But, it works. Maybe not enough to be merged yet, but let's discuss.

So the main parts:
- `fetch_sources.sh` automates the pulling down of the source files. That saves a lot of hassle :)
- `build_sfbaudioengine_frameworks.sh` got a lot of love, but it's the same file in spirit - it iterates over `.xcodeproj`s to build them
- `assemble.sh` pulls the built items into the required shape to be dropped directly into `SFBAudioEngine`

I also removed APE from the source tree, and added it as a downloadable.

Big TODOs are:
- clean up unused targets in `.xcodeproj`s
- removed unused libs (seems there are a lot of things that no one's using anymore, but it might be useful to keep around for anyone that wants 'em. Eh.)
- iOS support

But, really, I just wanted to get this out there in case it helps someone else. @sbooth, if you're using another script to generate it these days (and I suspect you must be!) I'd love to be using that instead. But, otherwise, here's a starting point :)

### CODE REVIEW

**Comment by sbooth** [comment]
I've actually moved away from using frameworks in my latest builds and now utilize static libraries for the dependencies, with the exception of GPL'd code which requires dynamic linking (`libmpg123`, `libsndfile`, and `libtta++`).  I try to use autoconf/automake/cmake or whatever native build system the project has from the command line.  In essence the script looks like this:

```
#!/bin/sh

PREFIX=`pwd`/macosx-x86_64-clang-libc++
CURDIR=`pwd`


for dir in \
XXX
do
  cd $dir && PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig/ CC=clang CXX=clang++ CPPFLAGS="-arch x86_64" CFLAGS="-std=gnu99" CXXFLAGS="-std=gnu++11 -stdlib=libc++" ./configure --disable-shared --prefix=$PREFIX && make install && cd $CURDIR
done
```

I definitely should automate the process and I like the idea of this PR.

**Comment by notjosh** [comment]
For what it's worth, the changes in this PR generate `.a` and `.dylib` as the latest SFBAudioEngine wants (and emits no `.framework` artefacts).

**Comment by JanX2** [comment]
Thank you @notjosh! I just gave the download script a whirl and it worked with one failure in the logs:

> ..patching tta (tta.patch)
> patching file libtta-c-src/filter.h
> patching file libtta-c-src/libtta.c
> Hunk #1 FAILED at 10.
> 1 out of 1 hunk FAILED -- saving rejects to file libtta-c-src/libtta.c.rej

**Comment by JanX2** [comment]
After pulling in 64bb42e, everything but libz built fine. This can’t all have to do with the commit. There probably is some dependencies not built in the necessary order.
The libz issue is:
> error: conflicting types for 'lseek'

**Comment by JanX2** [comment]
BTW: Why dylibs instead of frameworks?

**Comment by notjosh** [comment]
Ah, you're quick :) c526788 will fix the the issue with `libz` (which, sorry, should have caught sooner but overlooked. D'oh!)

**Comment by notjosh** [comment]
> BTW: Why dylibs instead of frameworks?

Dunno, that's what `SFBAudioEngine` is pulling in. At a guess, it's probably what the dependencies generate natively, without having to tinker too much around with OS X/Xcode specifics.

**Comment by JanX2** [comment]
Ah. That makes sense. I had been using these frameworks for Play.

**Comment by notjosh** [comment]
There's no reason it can't be configured to output both(/all incl static), but it didn't fit the use case of working with `SFBAudioEngine`. The `.framework` targets still exist, but I haven't tested any/many of them so are probably broken.

But, as per @sbooth's comment above, the approach of using Xcode projects kinda sucks. Using the native build tools for each project is far less of a maintenance burden going forward. (In which case you'd lose `.framework`).

I won't do a whole lot more on this at this point though, so that'd be up to you for now.

**Comment by JanX2** [comment]
It should be reasonable easy to adapt the Play project to use static and dylibs. Thanks for all your work! The download script could be useful in several places. :)

**Comment by mathbunnyru** [comment]
@notjosh are you sure instructions are correct? My ../SFBAudioEngine/Frameworks folder contains only empty subfolders. Then I launch ./assemble.sh ../SFBAudioEngine/Frameworks/ and it says a lot of messages like cp: ../SFBAudioEngine/Frameworks//build/sndfile/include/*: No such file or directory

**Comment by mathbunnyru** [comment]
I'm pretty sure it just doesn't work with latest Xcode. Can you somehow update these scripts, please? I want to be able to build SFBAudioEngine. I love Decibel and to make it better I want to be able to build SFBAudioEngine and to find some bugs.

**Comment by JanX2** [comment]
@mathbunnyru You can try and run `./build_sfbaudioengine_frameworks.sh ../SFBAudioEngine/Frameworks` first. That’s the step that builds the actual binaries before assembling the frameworks. The files are not there to be copied, because the have not ben compiled in, yet. 

@notjosh Currently, `mp4v2` fails for me:
> SVN exporting mp4v2 (501): http://mp4v2.googlecode.com/svn/trunk/
> svn: E170013: Unable to connect to a repository at URL 'http://mp4v2.googlecode.com/svn/trunk'
> svn: E160013: '/svn/trunk' path not found

**Comment by mathbunnyru** [comment]
@JanX2 the problem is I run that script in the beginning and it doesn't compile in correct folders. Maybe it's because I use Xcode 8 and options of xcodebuild have changed?

**Comment by mathbunnyru** [comment]
@notjosh any chances you will update scripts to work with Xcode 8 on MacOS Sierra, please?

**Comment by mathbunnyru** [comment]
@notjosh any chances you will update scripts to work with Xcode 8 on MacOS Sierra, please?

**Comment by notjosh** [comment]
@mathbunnyru @JanX2 Hi! Sorry, life got busy through December, so didn't get a chance. If I get some time this week, I'll take a look (though, no promises I'll actually be able to fix it quickly! Xcode is a pain sometimes! ;))

**Comment by mathbunnyru** [comment]
@notjosh thanks!

**Comment by notjosh** [comment]
@JanX2  I just pushed a patch (ec74190) to catch any of the dependency 404s. Should be okay now!

@mathbunnyru I'm not sure what error you're hitting. I've got the latest Xcode, and the build works fine for me from a fresh clone:

```
$ xcodebuild -version
Xcode 8.2.1
Build version 8C1002

$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.12.2
BuildVersion:	16C67

$ git clone https://github.com/notjosh/AudioFrameworks.git; \
cd ./AudioFrameworks; \
./fetch_sources.sh; \
mkdir -p /tmp/sfb/output; \
./build_sfbaudioengine_frameworks.sh /tmp/sfb/output; \
./assemble.sh /tmp/sfb/output; \
ls -l /tmp/sfb/output/dist/Libraries/macosx-x86_64-clang-libc++/lib/
# ... wait a few minutes ...
total 214928
-rw-r--r--  1 joshua  wheel   1430984 12 Jan 21:34 libFLAC.a
-rw-r--r--  1 joshua  wheel   1256392 12 Jan 21:34 libdumb.a
-rw-r--r--  1 joshua  wheel   1448000 12 Jan 21:34 libmac.a
-rw-r--r--  1 joshua  wheel  49145552 12 Jan 21:34 libmp4v2.a
-rw-r--r--  1 joshua  wheel    381488 12 Jan 21:34 libmpcdec.a
-rwxr-xr-x  1 joshua  wheel    408744 12 Jan 21:34 libmpg123.0.dylib
-rw-r--r--  1 joshua  wheel    105424 12 Jan 21:34 libogg.a
-rw-r--r--  1 joshua  wheel   2002080 12 Jan 21:34 libopus.a
-rw-r--r--  1 joshua  wheel    177384 12 Jan 21:34 libopusfile.a
-rwxr-xr-x  1 joshua  wheel    800720 12 Jan 21:34 libsndfile.1.dylib
-rw-r--r--  1 joshua  wheel   1197200 12 Jan 21:34 libspeex.a
-rw-r--r--  1 joshua  wheel  49383576 12 Jan 21:34 libtag.a
-rwxr-xr-x  1 joshua  wheel     77484 12 Jan 21:34 libtta++.0.dylib
-rw-r--r--  1 joshua  wheel    956192 12 Jan 21:34 libvorbis.a
-rw-r--r--  1 joshua  wheel    144320 12 Jan 21:34 libvorbisfile.a
-rw-r--r--  1 joshua  wheel    847536 12 Jan 21:34 libwavpack.a
-rw-r--r--  1 joshua  wheel    248432 12 Jan 21:34 libz.a
```

**Comment by JanX2** [comment]
Thanks @notjosh!

**Comment by mathbunnyru** [comment]
@notjosh thank you! Everything works! 👍 
@sbooth please, take a look. Thank you for your work. Maybe it's time to spend some time to update SFBAudioEngine and, more importantly, Decibel.

**Comment by sbooth** [comment]
This is great work, thanks @notjosh!

Looking at this PR got me wondering if it might make sense to get rid of the Xcode build process for libraries that natively build on macOS on their own.  Regardless, I think that should be a separate PR.

**Pull request merged**
