### PR TITLE
Update some sources

### PR DESCRIPTION
**Pull request by mathbunnyru**
I updated some sources which are easily updated.
I didn't check github based sources.

Sources, which also can be updated, but with some changes to Xcode or patches (I'm not familiar with either). I hope you'll take a look at these one to github based ones:

TTA_VERSION="2.1"
TTA_PLUS_PLUS_VERSION="2.1"
FLAC_VERSION="1.2.1"
MPG123_VERSION="1.23.8"
SNDFILE_VERSION="1.0.27"
SPEEX_VERSION="1.2.0"
WAVPACK_VERSION="5.0.0"

### CODE REVIEW

**Comment by mathbunnyru** [comment]
@sbooth please, tell me what you think about this pr. I think it would be a good idea to rebuild AudioEngine and then rebuild Decibel with new versions of libraries.

**Comment by mathbunnyru** [comment]
@sbooth is there any chance that Decibel users will have modern libraries? Please, tell je what you think about decibel future.

**Comment by JanX2** [comment]
@sbooth Please check!

**Comment by sbooth** [comment]
SFBAudioEngine now uses https://github.com/sbooth/AudioXCFrameworks

**Pull request closed without merging**
